#docker-compose up/down -d
# to specify a file, run docker-compose -f filename.yaml
# to rebuild image, add --build in after docker-compose up
version: '3'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: react_con
    ports:
      - '80:3000'
    volumes:
      - ./src:/app/src 
    env_file:
      - ./.env
